### ISSUE TITLE
"is_zero" is undefined running resnet50 script.

### ISSUE THREAD

**Issue by mrdvince** [NodLabs/dSHARK#23]
To reproduce...

cloned the repo and tried running the examples both resnet and minilm.

I keep getting
 ```
RuntimeError: required keyword attribute 'is_zero' is undefined
```
seems to have something to do with ModuleBuilder  -> mb.import_module(module._c, class_annotator)
env
Using the [Apple Silicon M1 Snapshot](https://github.com/llvm/torch-mlir/releases/download/snapshot-m1-20220418.396/torch_mlir-0.0.1-cp39-cp39-macosx_12_0_arm64.whl) version of torch-mlir.
Running on M1 macbook, python 3.9

attached screenshot of both resnet50_script and minilm

Disclaimer: new to torch-mlir

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/24603541/164107682-7e20eef8-7083-47a3-8dcc-3858fce849d1.png">

**Comment by powderluv** [comment]
Thanks for reporting. I am in the process of getting the SHARK binaries in a pip package. Did you build SHARK from src ?

**Comment by mrdvince** [comment]
I think I did, I just kept trying stuff until I couldn't get any errors, still a noob at this.

I will wait for the pip binaries instead.

**Comment by dan-garvey** [comment]
I ran into something similar when my torch was out of date.
If you're interested in continuing to try:

check your pip list and see if torch is something older than:
torch                        1.12.0.dev20220419+cpu

if so:
1. navigate to torch-mlir
2. have your venv active
3. git fetch
4. git checkout origin/main
5. pip uninstall torch torchvision torchaudio
6. pip install -r requirements.txt --no-cache-dir
7. cmake --build build
8. run example script

**Comment by mrdvince** [comment]
@dan-garvey  I had torch==1.12.0.dev20220418, switching to 1.12.0.dev20220419, runs for resnet50 but for the minilm_jit example getting a segmentation fault.

Unrelated: based on the blog from nod, it shows the examples running on the M1 GPU, looking at the examples I see cpu, cuda and vulkan backends, which backend should be used for this to run on the GPU?
